config/routes.rb
Gemmapp::Application.routes.draw do
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]

    match '/join', :to => 'users#new'
    match '/signin', :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/about', :to => 'pages#about'
    match '/contacts', :to => 'pages#contacts'

    root :to => "pages#home"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  surname            :string(255)
#  nickname           :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'

EMAIL_VALIDATION_TEMPLATE = /^[\w.+-]+@[a-z\d.-]+\.[a-z]{2,4}$/i
MAXIMUM_LENGTH_FOR_NAMES = 64
MINIMUM_LENGTH_FOR_PASSWORD = 8
MAXIMUM_LENGTH_FOR_PASSWORD = 255

class User < ActiveRecord::Base
    attr_accessor :password
    attr_accessible :name,
                    :surname,
                    :nickname,
                    :email,
                    :password,
                    :password_confirmation

    validates :name, :presence => true,
                     :length =>  { :maximum => MAXIMUM_LENGTH_FOR_NAMES }

    validates :surname, :length =>  { :maximum => MAXIMUM_LENGTH_FOR_NAMES }

    validates :nickname, :length =>  { :maximum => MAXIMUM_LENGTH_FOR_NAMES }

    validates :email, :presence => true,
                      :format => { :with => EMAIL_VALIDATION_TEMPLATE },
                      :uniqueness => { :case_sensitive => false }

    validates :password, :presence => true,
                         :confirmation => true,
                         :length =>  { :within =>
                            MINIMUM_LENGTH_FOR_PASSWORD..MAXIMUM_LENGTH_FOR_PASSWORD}

    before_save :encrypt_password

    def self.authenticate(email, password)
        user = find_by_email(email)
        (user && user.has_password?(password)) ? user : nil
    end

    def self.authenticate_with_remember_token(id, salt)
        user = User.find_by_id(id)
        (user && user.salt == salt) ? user : nil
    end

    # Checks if the submitted password matches the stored password.
    def has_password?(submitted_password)
        encrypted_password == encrypt(submitted_password)
    end

    def full_name
        return "#{nickname} (#{personal_name})" unless nickname.blank?
        personal_name
    end

    def short_name
        return nickname unless nickname.blank?
        personal_name
    end

    private
        def encrypt_password
            self.salt = make_salt unless has_password?(password)
            self.encrypted_password = encrypt(password)
        end

        def make_salt
            secure_hash("#{Time.now.utc}--#{password}")
        end

        def encrypt(text)
            secure_hash("#{salt}--#{text}")
        end

        def secure_hash(text)
            Digest::SHA2.hexdigest(text)
        end

        def personal_name
            name + ((surname.blank?) ? "" : " #{surname}")
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
    include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @page_name = __method__.capitalize
    end

    def about
        @page_name = __method__.capitalize
    end

    def contacts
        @page_name = __method__.capitalize
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    SIGN_IN_PAGE_NAME = 'Sign In'

    def new
        @page_name = SIGN_IN_PAGE_NAME
    end

    def create
        email = params[:session][:email]
        pwd = params[:session][:password]
        user = User.authenticate(email, pwd)

        if user
            sign_in user
            redirect_to user
        else
            @page_name = SIGN_IN_PAGE_NAME
            flash.now[:error] = 'Email e/o password non validi'
            render 'new'
        end
    end

    def destroy
        sign_out
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    NEW_USER_PAGE_NAME = 'Join'
    WELCOME_MESSAGE = "Benvenuto in Gemmapp!"

    def new
        @user = User.new
        @page_name = NEW_USER_PAGE_NAME
    end

    def show
        @user = User.find(params[:id])
        @page_name = @user.short_name
    end

    def create
        @user = User.new(params[:user])
        if @user.save
            sign_in @user
            flash[:success] = WELCOME_MESSAGE
            redirect_to @user
        else
            @page_name = NEW_USER_PAGE_NAME
            render 'new'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    APP_NAME = "Gemmapp"

    def page_title
        APP_NAME + ((@page_name.blank?) ? "" : " | #{@page_name}")
    end

    def logo
        image_tag("logo.png", :size => "76x67", :alt => APP_NAME, :class => "round")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        cookies.permanent.signed[:remember_token] = [user.id, user.salt]
        self.current_user = user
    end

    def sign_out
        cookies.delete(:remember_token)
        self.current_user = nil
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
        @current_user ||= user_from_remember_token
    end

    private

        def user_from_remember_token
            User.authenticate_with_remember_token(*remember_token)
        end

        def remember_token
            cookies.signed[:remember_token] || [nil, nil]
        end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { :size => 75 })
        gravatar_image_tag(
            user.email.downcase, #TODO ??? Forzarlo sempre a downcase al momento del salvataggio?
            :alt => h(user.name),
            :class => "gravatar",
            :gravatar => options)
    end
end

app/views/layouts/_footer.html.erb
<footer>
    <nav class="round">
        <ul>
            <li>&copy; Riccardo Contri 2011</li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contatti", contacts_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <%= link_to logo, root_path %>
    <nav class="round">
        <ul>
            <li><%= link_to "Home", root_path, :id => "home_link" %></li>
            <% if current_user.nil? %>
                <li><%= link_to "Entra", signin_path, :id => "signin_link" %></li>
            <% else %>
                <li><%= link_to current_user.short_name, user_path(current_user), :id => "profile_link" %></li>
                <li><%= link_to "Esci", signout_path, :id => "signout_link" %></li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]>
    <%= stylesheet_link_tag 'blueprint/ie' %>
<![endif]-->
<%= stylesheet_link_tag 'gemmapp', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
    <title><%= page_title %></title>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
</head>

<body>
    <div class="container">
        <%= render 'layouts/header' %>
        <section class="round">
            <% flash.each do |key, value| %>
                <%= content_tag(:div, value, :class => "flash #{key}") %>
            <% end %>
            <%= yield %>
        </section>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contacts.html.erb
<h1>Pages#contacts</h1>
<p>Find me in app/views/pages/contacts.html.erb</p>

app/views/pages/home.html.erb
<div id="page" class="main_page">
  <div id="content">
    <div id="header">
      <h1>Benvenuti in Gemmapp</h1>
      <h2></h2>
    </div>

    <div id="getting-started">
      <h3>Per cominciare</h3>
      <p>Se sei già iscritto, puoi <%= link_to "entrare", "#", :class => "round" %>. Altrimenti</p>
      <%= link_to "Unisciti a noi!", join_path, :class => "join_button round" %>
    </div>
  </div>

  <div id="footer">&nbsp;</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <h2>Per proseguire è necessario correggere i seguenti errori:</h2>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Unisciti a noi</h1>

<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="field">
        <%= f.label :name, "Nome" %><br/>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :surname, "Cognome" %><br/>
        <%= f.text_field :surname %>
    </div>
    <div class="field">
        <%= f.label :nickname %><br/>
        <%= f.text_field :nickname %>
    </div>
    <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br/>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation, "Conferma password" %><br/>
        <%= f.password_field :password_confirmation %>
    </div>

    <p><i>* Campo richiesto</i></p>

    <div class="actions">
        <%= f.submit "Iscriviti!" %>
    </div>

<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
    <tr>
        <td class="main">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.full_name %>
            </h1>
        </td>
        <td class="sidebar round">
            Nome: <strong><%= @user.name %></strong><br/>
            Cognome: <strong><%= @user.surname %></strong><br/>
            Nickname: <strong><%= @user.nickname %></strong><br/>
            URL:  <%= link_to user_path(@user), @user %>
        <td/>
</table>